### PR TITLE
Upgrade react and react native packages

### PR DESCRIPTION
**Pull request by vargasjona**
This pull request upgraded android and ios folders for compatibility due to this package was generating conflicts when I was trying to install it on the latest react-native.

    "react": "17.0.2",
    "react-native": "0.66.4"
    
This is the result

react-native-rasa

### CODE REVIEW

**Comment by hungvu193** [comment]
Hi @jonra1993, did you test on IOS too?

**Comment by vargasjona** [comment]
> Hi @jonra1993, did you test on IOS too?

Hello @hungvu193 yes, I tested on a simulator running a local rasa server with ngrok. It is working correctly.

Screen Recording 2021-12-15 at 8 43 26 PM

**Comment by hungvu193** [comment]
@jonra1993 perfect.

**Comment by vargasjona** [comment]
@hungvu193  thanks for approving the pull request. I have a question related to licensing I see it is using GPL v3 is there any plan to change it to Apache 2.0 or MIT as react-native-gifted-chat uses? I am willing to help you add improvements to this library as PR. Currently, I am working on a client project connecting Rasa with a react native app, but GPL3 is not permitted for our client due to this https://youtu.be/sQIVclmxvdQ .

**Comment by hungvu193** [comment]
@jonra1993 no problem, I will change it to MIT at next release, will be next few days, I'm busy on another project, but I will release ASAP.

**Pull request merged**
