### PR TITLE
Add restart messages, bot and checkboxes

### PR DESCRIPTION
**Pull request by vargasjona**
This PR has the following changes:

Add forwardRef to RasaChat so it can handle inner functions from parent components
Add resetMessages method to clear messages
Add resetBot method to reset bot (Rasa bot will need a /reset intent which cleans conversation using action)
Add checkbox
Add video responses
Update RAEDME
Update License
Add Rasa example

demo

### CODE REVIEW

**Comment by hungvu193** [comment]
I saw the warning when you sent the image, I think that the light-box problem, can you please try to resolve that issue by using this comment https://github.com/FaridSafi/react-native-gifted-chat/issues/1825#issuecomment-718463680 😄 ?

**Review by hungvu193 — APPROVED** [review]

**Comment by vargasjona** [comment]
> FaridSafi/react-native-gifted-chat#1825 (comment)

Hello @hungvu193 yes sure I am going to solve it

**Comment by vargasjona** [comment]
The patch you suggested solved the warning.

demo

**Comment by hungvu193** [comment]
I'm glad to hear that 👍

**Pull request merged**
